#!/usr/bin/env bash
# Download a Google Font and self-host it in this Hugo project.
#
# Usage: fetch-google-font.sh "Family Name" "400,700"
#
# - Downloads the .woff2 files into static/fonts/<slug>/
# - Writes assets/css/components/fonts.css with @font-face rules pointing at the
#   local files (font-display: swap), so the browser never calls Google.
#
# Only one custom family is hosted at a time; re-running replaces it.
# Run from the project root.
set -euo pipefail

family="${1:?Usage: fetch-google-font.sh \"Family Name\" \"400,700\"}"
weights="${2:-400,700}"

root="$(pwd)"
[ -d "$root/assets/css/components" ] || {
  echo "Run this from the project root (no assets/css/components/ here)." >&2
  exit 1
}

slug="$(printf '%s' "$family" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
css_out="$root/assets/css/components/fonts.css"
fonts_dir="$root/static/fonts/$slug"

# Build the Google Fonts CSS API URL.
fam_param="$(printf '%s' "$family" | sed 's/ /+/g')"
wght="$(printf '%s' "$weights" | tr ',' ';')"
api="https://fonts.googleapis.com/css2?family=${fam_param}:wght@${wght}&display=swap"

# A modern desktop User-Agent makes the API return woff2 (its smallest format).
ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

echo "Fetching $family ($weights) from Google Fonts…"
css="$(curl -fsSL -A "$ua" "$api")" || {
  echo "Error: couldn't fetch '$family' with weights '$weights'." >&2
  echo "Check the spelling and available weights on https://fonts.google.com/." >&2
  exit 1
}

# Reset any previously self-hosted font, then download the new one.
rm -rf "$root/static/fonts"
mkdir -p "$fonts_dir"

i=0
while IFS= read -r url; do
  [ -z "$url" ] && continue
  i=$((i + 1))
  file="$slug-$i.woff2"
  curl -fsSL "$url" -o "$fonts_dir/$file"
  css="${css//$url//fonts/$slug/$file}"
done < <(printf '%s\n' "$css" | grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' | awk '!seen[$0]++')

if [ "$i" -eq 0 ]; then
  echo "Error: no woff2 files found in the Google Fonts response." >&2
  exit 1
fi

{
  echo "/* Self-hosted Google Font: $family ($weights)."
  echo "   Generated by the change-font skill — re-run it to switch fonts."
  echo "   Point --font-body / --font-heading at \"$family\" in variables.css. */"
  echo
  printf '%s\n' "$css"
} > "$css_out"

echo "Done: downloaded $i file(s) to static/fonts/$slug/ and wrote $(basename "$css_out")."
echo "Next: set --font-body / --font-heading to \"$family\" in assets/css/variables.css."
